### ISSUE TITLE
WHO DO YOU THINK YOU ARE

### ISSUE THREAD

**Issue by Aplet123** [NonZeroConstants/website#1]
HOW DARE YOU USE THE MARQUEE TAG YOU TAKE THIS DOWN RIGHT NOW OTHERWISE I WILL TAKE YOUR MARQUEE TAGS AND DELETE THEM MYSELF. YOU HAVE SINNED.

**Comment by NonZeroConstants** [comment]
We do not negotiate with terrorists.
